language: php

php:
  - "7.1"

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

dist: trusty

  # Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=glowing-thunder-215513
    - CLUSTER_NAME_PRD=siwecoscluster
    - CLOUDSDK_COMPUTE_ZONE=europe-west1-b


jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$DOCKER_IMAGE" .
      - docker images
      - docker tag "$DOCKER_IMAGE" "$DOCKER_REPO"/"$DOCKER_IMAGE":"$TRAVIS_BRANCH"
      - docker push "$DOCKER_REPO"/"$DOCKER_IMAGE":"$TRAVIS_BRANCH"

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: chmod +x deploy-staging.sh && ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: chmod +x deploy-master.sh && ./deploy-master.sh
    skip_cleanup: true
    on:
      branch: master
